services:
  minio:
    container_name: minio
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_DEFAULT_BUCKETS=localhost
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - minio_network
    volumes:
      - 'minio:/bitnami/minio/data'

  database:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - minio_network
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - minio_network
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - minio_network
  sidekiq:
    image: decidim-app:latest
    command: [ "bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml" ]
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DECIDIM_HOST=localhost
      - REDIS_URL=redis://redis:6379
      - MEMCACHE_SERVERS=memcached:11211
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_LOG_LEVEL=debug
      - ASSET_HOST=localhost:3000
      - FORCE_SSL=1
      - ENABLE_LETTER_OPENER=1
      - SEED=true
      - DEFACE_ENABLED=false
      - QUESTION_CAPTCHA_HOST=
      - ENABLE_RACK_ATTACK=0
      - PUMA_MIN_THREADS=5
      - PUMA_MAX_THREADS=5
      - PUMA_WORKERS=4
      - PUMA_PRELOAD_APP=true
      - RAILS_SESSION_STORE=active_record
      - GEOCODER_LOOKUP_API_KEY=${GEOCODER_LOOKUP_API_KEY}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - AVAILABLE_LOCALES=${AVAILABLE_LOCALES}
      - OBJECTSTORE_S3_HOST=minio:9000
      - SCALEWAY_BUCKET_NAME=localhost
      - SCALEWAY_ID=O35LJJVOztztLYc9Kufu
      - SCALEWAY_TOKEN=x6CdylbphThMlZwfuDUNX9fwxlcgwpToxng3BFgR
    depends_on:
      - app
    volumes:
      - shared-volume:/app
    links:
      - database
      - redis
    networks:
      - minio_network
  app:
    image: decidim-app:latest
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DECIDIM_HOST=localhost
      - REDIS_URL=redis://redis:6379
      - MEMCACHE_SERVERS=memcached:11211
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_LOG_LEVEL=debug
      - ASSET_HOST=localhost:3000
      - FORCE_SSL=1
      - ENABLE_LETTER_OPENER=1
      - SEED=true
      - DEFACE_ENABLED=false
      - QUESTION_CAPTCHA_HOST=
      - ENABLE_RACK_ATTACK=0
      - PUMA_MIN_THREADS=5
      - PUMA_MAX_THREADS=5
      - PUMA_WORKERS=4
      - PUMA_PRELOAD_APP=true
      - RAILS_SESSION_STORE=active_record
      - GEOCODER_LOOKUP_API_KEY=${GEOCODER_LOOKUP_API_KEY}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - AVAILABLE_LOCALES=${AVAILABLE_LOCALES}
      - OBJECTSTORE_S3_HOST=minio:9000
      - SCALEWAY_BUCKET_NAME=localhost
      - SCALEWAY_ID=minioadmin
      - SCALEWAY_TOKEN=minioadmin
    volumes:
      - shared-volume:/app
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
      - memcached
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge

volumes:
  shared-volume: { }
  pg-data: { }
  redis-data: { }
  minio:
    driver: local