# frozen_string_literal: true

module Decidim
  module Content
    class OrganizationSerializer < Decidim::Content::BaseContentSerializer
      def serialize
        {
          uid: uid(resource),
          host: resource.host,
          reference_prefix: resource.reference_prefix,
          created_at: resource.created_at,
          updated_at: resource.updated_at,
          default_locale: resource.default_locale,
          available_locales: resource.available_locales,
          time_zone: resource.time_zone,
          name: normalize_translated_attribute(resource.name),
          description: normalize_translated_attribute(resource.description),
          logo: blob_url(resource.logo, resource),
          favicon: blob_url(resource.favicon, resource),
          official_url: resource.official_url,
          official_img_footer: blob_url(resource.official_img_footer, resource),
          twitter_handler: resource.twitter_handler,
          instagram_handler: resource.instagram_handler,
          facebook_handler: resource.facebook_handler,
          youtube_handler: resource.youtube_handler,
          github_handler: resource.github_handler,
          # cta_button_text: resource.cta_button_text,
          # cta_button_path: resource.cta_button_path,
          # enable_omnipresent_banner: resource.enable_omnipresent_banner,
          # omnipresent_banner_title: resource.omnipresent_banner_title,
          # omnipresent_banner_short_description: resource.omnipresent_banner_short_description,
          # omnipresent_banner_url: resource.omnipresent_banner_url,
          # highlighted_content_banner_enabled: resource.highlighted_content_banner_enabled,
          # highlighted_content_banner_title: resource.highlighted_content_banner_title,
          # highlighted_content_banner_short_description: resource.highlighted_content_banner_short_description,
          # highlighted_content_banner_action_title: resource.highlighted_content_banner_action_title,
          # highlighted_content_banner_action_subtitle: resource.highlighted_content_banner_action_subtitle,
          # highlighted_content_banner_action_url: resource.highlighted_content_banner_action_url,
          # highlighted_content_banner_image: blob_url(resource.highlighted_content_banner_image, resource),
          # tos_version: resource.tos_version,
          # badges_enabled: resource.badges_enabled,
          # send_welcome_notification: resource.send_welcome_notification,
          # welcome_notification_subject: resource.welcome_notification_subject,
          # welcome_notification_body: resource.welcome_notification_body,
          # id_documents_methods: resource.id_documents_methods,
          # id_documents_explanation_text: resource.id_documents_explanation_text,
          # user_groups_enabled: resource.user_groups_enabled,
          # deepl_api_key: resource.deepl_api_key,
          # comments_max_length: resource.comments_max_length,
          # rich_text_editor_in_public_views: resource.rich_text_editor_in_public_views,
          # admin_terms_of_service_body: resource.admin_terms_of_service_body,
          # enable_machine_translations: resource.enable_machine_translations,
          # machine_translation_display_priority: resource.machine_translation_display_priority,
          # enable_participatory_space_filters: resource.enable_participatory_space_filters,
          # delete_admin_logs: resource.delete_admin_logs,
          # delete_admin_logs_after: resource.delete_admin_logs_after,
          # delete_inactive_users: resource.delete_inactive_users,
          # delete_inactive_users_email_after: resource.delete_inactive_users_email_after,
          # delete_inactive_users_after: resource.delete_inactive_users_after,
          # secondary_hosts: resource.secondary_hosts,
          content_security_policy: resource.content_security_policy,
          # external_domain_allowlist: resource.external_domain_allowlist,
          header_snippets: resource.header_snippets,
          # colors: resource.colors,
          file_upload_settings: resource.file_upload_settings,
          smtp_settings: resource.smtp_settings.slice("from", "from_email", "from_label"),
          available_authorizations: resource.available_authorizations,
          users_registration_mode: resource.users_registration_mode,
          force_users_to_authenticate_before_access_organization: resource.force_users_to_authenticate_before_access_organization,
          extra_user_fields: resource.extra_user_fields,
          omniauth_settings: resource.omniauth_settings
        }
      end
    end
  end
end
