name: "Deploy production"
on: [ workflow_dispatch ]

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 3.0.6
  RAILS_ENV: test
  NODE_VERSION: 16.9.1
  RUBYOPT: '-W:no-deprecated'

jobs:
  deploy_master:
    if: "github.ref == 'refs/heads/master'"
    name: Deploy master branch on production instance
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible playbook
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.ANSIBLE_HOST }}
          username: ${{ secrets.ANSIBLE_USERNAME }}
          key: ${{ secrets.ANSIBLE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ansible-playbook -u ${{ secrets.ANSIBLE_USERNAME }} --private-key="~/.ssh/ansible-deploy/ansible-deploy" -i /home/${{ secrets.ANSIBLE_USERNAME }}/ansible/decidim/inventories/production.yml /home/${{ secrets.ANSIBLE_USERNAME }}/ansible/decidim/playbooks/update_decidim_app.yml
