name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push_image_prod:
    name: Build and push image to Registry
    runs-on: ubuntu-latest
    steps:

      - uses: OpenSourcePolitics/build-and-push-images-action@master
        with:
          registry: ${{ vars.REGISTRY_ENDPOINT }}
          namespace: ${{ vars.REGISTRY_NAMESPACE }}
          password: ${{ secrets.TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          tag: "${{github.ref_name}}"