on:
  workflow_call:
    inputs:
      ruby_version:
        required: false
        description: 'Ruby version'
        default: "3.2.2"
        type: string

jobs:
  sast:
    name: Bundler Audit
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - name: Bundler Audit
        run: |
          bundle exec rake bundle:audit