name: Tests 4
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 2.7.1
  NODE_VERSION: 16.9.1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RAILS_ENV: test
      # Set locales available for i18n tasks
      ENFORCED_LOCALES: "en,fr"
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: "github.ref != 'refs/heads/master' || github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Create db
        run: |
          bundle exec rails db:create db:schema:load
      - name: Cache Assets
        id: assets-cache
        uses: actions/cache@v1
        with:
          path: public/packs-test
          key: ${{ runner.os }}-assets-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-assets-
      - name: Compile Assets
        shell: bash
        run: |
          if [[ ! -d public/packs-test ]]; then
            bundle exec rails webpacker:compile
          else
            echo "No need to compile assets."
          fi
      - run: mkdir -p ./spec/tmp/screenshots
        name: Create the screenshots folder
      - uses: nanasess/setup-chromedriver@v1.0.1
      - run: bundle exec rspec $(bundle exec rake test:split\[4\])
        name: RSpec
      - run: ./.github/upload_coverage.sh $DECIDIM_MODULE $GITHUB_EVENT_PATH
        name: Upload coverage
      - uses: actions/upload-artifact@v2-preview
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
